/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemadetiendaropa;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nicol
 */
public class frmSistemadeTiendaRopa extends javax.swing.JFrame {

    /**
     * Creates new form frmSistemadeTiendaRopa
     */
    public frmSistemadeTiendaRopa() {
        initComponents();
        this.tabladetalles.setModel(modelo);
        this.modelo.addColumn("NACIONALIDAD");
        this.modelo.addColumn("GENERO");
        this.modelo.addColumn("TALLAS");
        this.modelo.addColumn("PRENDAS");
        this.modelo.addColumn("CANTIDAD");
        this.modelo.addColumn("PRECIO UNITARIO");
        this.modelo.addColumn("TOTAL A PAGAR");
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbonacionalidad = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        botonh = new javax.swing.JRadioButton();
        botonm = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        cbotallas = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtprenda = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        btngenerar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladetalles = new javax.swing.JTable();
        btnlimpiartabla = new javax.swing.JButton();
        btnquitar = new javax.swing.JButton();
        btnnetopagar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtnetopagar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sistema Tienda de Ropa");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Descuentos y/o Promociones"));

        jLabel2.setText("Nacional");

        jLabel3.setText("HOMBRE TALLA: S=0.05, M=0.07, L=0.10");

        jLabel4.setText("MUJER TALLA   : S=0.04,M=0.09,L=0.12");

        jLabel5.setText("Extranjeros");

        jLabel6.setText("HOMBRE TALLA: S=0.04,M=0.09,L=0.12");

        jLabel7.setText("MUJER TALLA   : S=0.05,M=O.07,L=0.10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Realizar Compra"));

        jLabel8.setText("Nacionalidad");

        cbonacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Peruano", "Extranjero" }));

        jLabel9.setText("Genero:");

        buttonGroup1.add(botonh);
        botonh.setText("Hombre");

        buttonGroup1.add(botonm);
        botonm.setText("Mujer");

        jLabel10.setText("Tallas:");

        cbotallas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "S", "M", "L" }));

        jLabel11.setText("Prenda");

        jLabel12.setText("Cantidad");

        jLabel13.setText("Precio");

        jLabel14.setText("Total a Pagar:");

        btngenerar.setText("Generar Compra");
        btngenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerarActionPerformed(evt);
            }
        });

        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(81, 81, 81)
                .addComponent(jLabel9)
                .addGap(129, 129, 129)
                .addComponent(jLabel10)
                .addGap(65, 65, 65)
                .addComponent(jLabel11)
                .addGap(51, 51, 51)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbonacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonh)
                        .addGap(18, 18, 18)
                        .addComponent(botonm)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btngenerar)
                        .addGap(61, 61, 61)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbotallas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlimpiar))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtprenda, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtprecio))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbonacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonh)
                        .addComponent(botonm))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbotallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtprenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btngenerar)
                    .addComponent(btnlimpiar)
                    .addComponent(jLabel14)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de Compras"));

        tabladetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabladetalles);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnlimpiartabla.setText("Limpiar Tabla");
        btnlimpiartabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiartablaActionPerformed(evt);
            }
        });

        btnquitar.setText("Quitar Compra");
        btnquitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitarActionPerformed(evt);
            }
        });

        btnnetopagar.setText("Neto a Pagar");
        btnnetopagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnetopagarActionPerformed(evt);
            }
        });

        jLabel15.setText("Neto a Pagar s/.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(btnlimpiartabla, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnquitar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnnetopagar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnetopagar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(418, 418, 418)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlimpiartabla)
                    .addComponent(btnquitar)
                    .addComponent(btnnetopagar)
                    .addComponent(jLabel15)
                    .addComponent(txtnetopagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerarActionPerformed
        // TODO add your handling code here:
        descuentos_hombres_peruanos();
        descuentos_mujeres_peruanas();
        descuentos_hombres_extranjeros();
        descuentos_mujeres_extranjeras();
        
        
        if(botonh.isSelected()){
            this.modelo.addRow(new Object[]{this.cbonacionalidad.getSelectedIndex(),"Hombre",
               this.cbotallas.getSelectedItem(),this.txtprenda.getText(),this.txtcantidad.getText(),
               this.txtprecio.getText(),this.txttotal.getText()});
        }
        else if(botonm.isSelected()){
             this.modelo.addRow(new Object[]{this.cbonacionalidad.getSelectedIndex(),"Mujer",
               this.cbotallas.getSelectedItem(),this.txtprenda.getText(),this.txtcantidad.getText(),
               this.txtprecio.getText(),this.txttotal.getText()});
        }        
    }//GEN-LAST:event_btngenerarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
        this.cbonacionalidad.setSelectedIndex(0);
        if(botonh.isSelected()){
        }
        if(botonm.isSelected()){
        }
        this.cbotallas.setSelectedIndex(0);
        this.txtprenda.setText("");
        this.txtcantidad.setText("");
        this.txtprecio.setText("");
        this.txttotal.setText("");
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnquitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitarActionPerformed
        // TODO add your handling code here:
        modelo.removeRow(this.tabladetalles.getSelectedRow());
    }//GEN-LAST:event_btnquitarActionPerformed

    private void btnlimpiartablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiartablaActionPerformed
        // TODO add your handling code here:
        int x=this.modelo.getRowCount();
        for (int y = 0; y <=x; y++){
            this.modelo.removeRow(0);
        }
        this.txtnetopagar.setText("");
    }//GEN-LAST:event_btnlimpiartablaActionPerformed

    private void btnnetopagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnetopagarActionPerformed
        // TODO add your handling code here:
        double sumatoria;
        double sumatorial=0;
        int totalrow=tabladetalles.getRowCount();
        totalrow-=1;
        for (int i = 0; i <= (totalrow); i++) {
            sumatoria=Double.parseDouble(String.valueOf(tabladetalles.getValueAt(i, 6)));
            sumatorial+=sumatoria;
        }
        txtnetopagar.setText("S. "+String.valueOf(sumatorial));
    }//GEN-LAST:event_btnnetopagarActionPerformed
DefaultTableModel modelo=new DefaultTableModel();
private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt){
    
}
public void descuentos_hombres_extranjeros(){
    double cantidad_s,precio_s,total_s,desc_s=0.04;
    double cantidad_m,precio_m,total_m,desc_m=0.09;
    double cantidad_l,precio_l,total_l,desc_l=0.12;
    //Selecciona S
    if(cbonacionalidad.getSelectedIndex()==2){
        if(this.botonh.isSelected()){
            if(cbotallas.getSelectedIndex()==1){
                cantidad_s=Double.parseDouble(this.txtcantidad.getText());
                precio_s=Double.parseDouble(this.txtprecio.getText());
                total_s=(precio_s*cantidad_s)-((cantidad_s*precio_s)*desc_s);
                this.txttotal.setText(String.valueOf(total_s));
            
        }
    }
    //Selecciona M    
    if(cbonacionalidad.getSelectedIndex()==2){
        if(this.botonh.isSelected()){
            if(cbotallas.getSelectedIndex()==2){
                cantidad_m=Double.parseDouble(this.txtcantidad.getText());
                precio_m=Double.parseDouble(this.txtprecio.getText());
                total_m=(precio_m*cantidad_m)-((cantidad_m*precio_m)*desc_m);
                this.txttotal.setText(String.valueOf(total_m));
            }
        }
    }
    //Selecciona L
    if(cbonacionalidad.getSelectedIndex()==2){
        if(this.botonh.isSelected()){
            if(cbotallas.getSelectedIndex()==3){
                cantidad_l=Double.parseDouble(this.txtcantidad.getText());
                precio_l=Double.parseDouble(this.txtprecio.getText());
                total_l=(precio_l*cantidad_l)-((cantidad_l*precio_l)*desc_l);
                this.txttotal.setText(String.valueOf(total_l));
            }
        }
    }
}

}public void descuentos_mujeres_extranjeras() {
    Double cantidad_s,precio_s,total_s,desc_s=0.05;
    Double cantidad_m,precio_m,total_m,desc_m=0.07;
    Double cantidad_l,precio_l,total_l,desc_l=0.10;
    //Selecciona S
    if(cbonacionalidad.getSelectedIndex()==2){
        if(this.botonm.isSelected()){
            if(cbotallas.getSelectedIndex()==1){
                cantidad_s=Double.parseDouble(this.txtcantidad.getText());
                precio_s=Double.parseDouble(this.txtprecio.getText());
                total_s=(precio_s*cantidad_s)-((cantidad_s*precio_s)*desc_s);
                this.txttotal.setText(String.valueOf(total_s));
            }
        }
    }
    //Seleccione M
    if(cbonacionalidad.getSelectedIndex()==2){
        if(this.botonm.isSelected()){
            if(cbotallas.getSelectedIndex()==2){
                cantidad_m=Double.parseDouble(this.txtcantidad.getText());
                precio_m=Double.parseDouble(this.txtprecio.getText());
                total_m=(precio_m*cantidad_m)-((cantidad_m*precio_m)*desc_m);
                this.txttotal.setText(String.valueOf(total_m));
            }
        }
    }
    //Seleccione L
    if(cbonacionalidad.getSelectedIndex()==2){
        if(this.botonm.isSelected()){
            if(cbotallas.getSelectedIndex()==3){
                cantidad_l=Double.parseDouble(this.txtcantidad.getText());
                precio_l=Double.parseDouble(this.txtprecio.getText());
                total_l=(precio_l*cantidad_l)-((cantidad_l*precio_l)*desc_l);
                this.txttotal.setText(String.valueOf(total_l));
            }
        }
    }
    
}    
    
public void descuentos_mujeres_peruanas() {
    double cantidad_s,precio_s,total_s,desc_s=0.04;
    double cantidad_m,precio_m,total_m,desc_m=0.09;
    double cantidad_l,precio_l,total_l,desc_l=0.12;
    //Selecciona S
    if(cbonacionalidad.getSelectedIndex()==1){
        if(this.botonm.isSelected()){
            if(cbotallas.getSelectedIndex()==1){
                cantidad_s=Double.parseDouble(this.txtcantidad.getText());
                precio_s=Double.parseDouble(this.txtprecio.getText());
                total_s=(precio_s*cantidad_s)-((cantidad_s*precio_s)*desc_s);
                this.txttotal.setText(String.valueOf(total_s));
            }
        }
    }
    //Selecciona M
    if(cbonacionalidad.getSelectedIndex()==1){
        if(this.botonm.isSelected()){
            if(cbotallas.getSelectedIndex()==2){
                cantidad_m=Double.parseDouble(this.txtcantidad.getText());
                precio_m=Double.parseDouble(this.txtprecio.getText());
                total_m=(precio_m*cantidad_m)-((cantidad_m*precio_m)*desc_m);
                this.txttotal.setText(String.valueOf(total_m));
            }
        }
    }
    //Selecciona L
    if(cbonacionalidad.getSelectedIndex()==1){
        if(this.botonm.isSelected()){
            if(cbotallas.getSelectedIndex()==3){
                cantidad_l=Double.parseDouble(this.txtcantidad.getText());
                precio_l=Double.parseDouble(this.txtprecio.getText());
                total_l=(precio_l*cantidad_l)-((cantidad_l*precio_l)*desc_l);
                this.txttotal.setText(String.valueOf(total_l));
            }
        }
    }
}
public void descuentos_hombres_peruanos(){
    double cantidad_s,precio_s,total_s,desc_s=0.05;
    double cantidad_m,precio_m,total_m,desc_m=0.07;
    double cantidad_l,precio_l,total_l,desc_l=0.10;
    //Selecciona S
    if(cbonacionalidad.getSelectedIndex()==1){
        if(this.botonh.isSelected()){
            if(cbotallas.getSelectedIndex()==1){
                cantidad_s=Double.parseDouble(this.txtcantidad.getText());
                precio_s=Double.parseDouble(this.txtprecio.getText());
                total_s=(precio_s*cantidad_s)-((cantidad_s*precio_s)*desc_s);
                this.txttotal.setText(String.valueOf(total_s));
                        
             
            }
        }
    }
    //Selecciona M
    if(cbonacionalidad.getSelectedIndex()==1){
        if(this.botonh.isSelected()){
            if(cbotallas.getSelectedIndex()==2){
                cantidad_m=Double.parseDouble(this.txtcantidad.getText());
                precio_m=Double.parseDouble(this.txtprecio.getText());
                total_m=(precio_m*cantidad_m)-((cantidad_m*precio_m)*desc_m);
                this.txttotal.setText(String.valueOf(total_m));
                        
             
            }
        }
    }
    //Selecciona L
    if(cbonacionalidad.getSelectedIndex()==1){
        if(this.botonh.isSelected()){
            if(cbotallas.getSelectedIndex()==3){
                cantidad_l=Double.parseDouble(this.txtcantidad.getText());
                precio_l=Double.parseDouble(this.txtprecio.getText());
                total_l=(precio_l*cantidad_l)-((cantidad_l*precio_l)*desc_l);
                this.txttotal.setText(String.valueOf(total_l));
                        
             
            }
        }
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSistemadeTiendaRopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSistemadeTiendaRopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSistemadeTiendaRopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSistemadeTiendaRopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmSistemadeTiendaRopa().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonh;
    private javax.swing.JRadioButton botonm;
    private javax.swing.JButton btngenerar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnlimpiartabla;
    private javax.swing.JButton btnnetopagar;
    private javax.swing.JButton btnquitar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbonacionalidad;
    private javax.swing.JComboBox<String> cbotallas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabladetalles;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtnetopagar;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtprenda;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
